/** Arayuz sabit metinleri - menu icerigi degil, uygulama metni. */
export const UI = {
  search:        { tr: 'Menüde ara', en: 'Search menu', ar: 'ابحث في القائمة', ru: 'Поиск в меню' },
  noResults:     { tr: 'Sonuç bulunamadı', en: 'No results', ar: 'لا توجد نتائج', ru: 'Ничего не найдено' },
  noResultsHint: { tr: 'Başka bir kelime deneyin.', en: 'Try another word.', ar: 'جرّب كلمة أخرى.', ru: 'Попробуйте другое слово.' },
  soldOut:       { tr: 'Tükendi', en: 'Sold out', ar: 'نفد', ru: 'Нет в наличии' },
  from:          { tr: 'başlayan', en: 'from', ar: 'يبدأ من', ru: 'от' },
  ingredients:   { tr: 'İçindekiler', en: 'Ingredients', ar: 'المكونات', ru: 'Состав' },
  portions:      { tr: 'Porsiyon', en: 'Portion', ar: 'الحصة', ru: 'Порция' },
  price:         { tr: 'Fiyat', en: 'Price', ar: 'السعر', ru: 'Цена' },
  close:         { tr: 'Kapat', en: 'Close', ar: 'إغلاق', ru: 'Закрыть' },
  addFav:        { tr: 'Listeme ekle', en: 'Add to my list', ar: 'أضف إلى قائمتي', ru: 'В мой список' },
  removeFav:     { tr: 'Listemden çıkar', en: 'Remove from list', ar: 'إزالة من القائمة', ru: 'Убрать из списка' },
  myList:        { tr: 'Listem', en: 'My list', ar: 'قائمتي', ru: 'Мой список' },
  myListEmpty:   { tr: 'Henüz bir şey eklemediniz.', en: 'Nothing added yet.', ar: 'لم تُضِف شيئًا بعد.', ru: 'Пока ничего не добавлено.' },
  myListHint:    { tr: 'Beğendiğiniz ürünlerin kalbine dokunun; burada birikir, garsona okuyabilirsiniz.',
                   en: 'Tap the heart on dishes you like; they collect here to show your waiter.',
                   ar: 'اضغط على القلب بجانب الأطباق التي تعجبك؛ ستتجمع هنا لتُظهرها للنادل.',
                   ru: 'Нажимайте на сердечко у понравившихся блюд — они соберутся здесь, чтобы показать официанту.' },
  clearList:     { tr: 'Listeyi temizle', en: 'Clear list', ar: 'مسح القائمة', ru: 'Очистить список' },
  hours:         { tr: 'Çalışma saatleri', en: 'Opening hours', ar: 'ساعات العمل', ru: 'Часы работы' },
  wifi:          { tr: 'Wifi şifresi', en: 'Wifi password', ar: 'كلمة سر الواي فاي', ru: 'Пароль Wi-Fi' },
  copy:          { tr: 'Kopyala', en: 'Copy', ar: 'نسخ', ru: 'Копировать' },
  copied:        { tr: 'Kopyalandı', en: 'Copied', ar: 'تم النسخ', ru: 'Скопировано' },
  loadError:     { tr: 'Menü şu anda yüklenemedi.', en: "Menu couldn't load right now.", ar: 'تعذّر تحميل القائمة الآن.', ru: 'Не удалось загрузить меню.' },
  retry:         { tr: 'Tekrar dene', en: 'Try again', ar: 'حاول مجددًا', ru: 'Повторить' },
  // --- Ana sayfa ---
  viewMenu:      { tr: 'Menüyü Gör', en: 'View Menu', ar: 'عرض القائمة', ru: 'Смотреть меню' },
  backHome:      { tr: 'Ana sayfa', en: 'Home', ar: 'الرئيسية', ru: 'Главная' },
  welcomeTitle:  { tr: 'Hoş geldiniz', en: 'Welcome', ar: 'أهلاً بكم', ru: 'Добро пожаловать' },
  welcomeText:   {
    tr: 'Çam ormanının içinde, Boğaz’a bakan bir sofra. Sabah serpme kahvaltı, akşam meşe kömüründe mangal; arada semaverde sınırsız çay.',
    en: 'A table in the pine forest, looking out over the Bosphorus. A spread breakfast in the morning, charcoal grill in the evening, and unlimited tea from the samovar in between.',
    ar: 'مائدة بين أشجار الصنوبر تطل على البوسفور. فطور مفتوح في الصباح، مشاوي على الفحم في المساء، وشاي بلا حدود من السماور.',
    ru: 'Стол в сосновом лесу с видом на Босфор. Утром — щедрый завтрак, вечером — гриль на углях, а между ними бесконечный чай из самовара.',
  },
  // Mekanin konumu - Anadolu Kavagi, Bogaz'in Anadolu yakasi.
  locationLine:  {
    tr: 'Anadolu Kavağı · Boğaz kıyısı',
    en: 'Anadolu Kavağı · on the Bosphorus',
    ar: 'أنادولو كافاغي · على البوسفور',
    ru: 'Анадолу Кавагы · на Босфоре',
  },
  directions:    { tr: 'Yol tarifi', en: 'Directions', ar: 'الاتجاهات', ru: 'Маршрут' },
  whatsOnMenu:   { tr: 'Menüde ne var', en: "What's on the menu", ar: 'ماذا في القائمة', ru: 'Что в меню' },
  pickCategory:  { tr: 'Bir bölüme dokunun', en: 'Tap a section', ar: 'اختر قسمًا', ru: 'Выберите раздел' },
  highlights:    { tr: 'Öne çıkanlar', en: 'Highlights', ar: 'أطباق مميزة', ru: 'Рекомендуем' },
  highlightsHint:{ tr: 'Kaydırarak inceleyin', en: 'Swipe to browse', ar: 'اسحب للتصفح', ru: 'Прокрутите' },
  findUs:        { tr: 'Bize ulaşın', en: 'Find us', ar: 'تواصل معنا', ru: 'Контакты' },

  // Marka sloganı - logodan geliyor.
  slogan:        { tr: 'Doğanın Kalbinde, Lezzetin Peşinde',
                   en: 'In the Heart of Nature, in Pursuit of Flavour',
                   ar: 'في قلب الطبيعة، سعياً وراء النكهة',
                   ru: 'В сердце природы, в поисках вкуса' },
  offlineNote:   { tr: 'Çevrimdışısınız — en son kaydedilen menü gösteriliyor.',
                   en: "You're offline — showing the last saved menu.",
                   ar: 'أنت دون اتصال — يتم عرض آخر قائمة محفوظة.',
                   ru: 'Вы офлайн — показано последнее сохранённое меню.' },
};
